services:
  # PostgresSQL database service
  db:
    image: postgres:latest
    ports:
        - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password

    # Adminer database management service (Visual interface for databases)
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"

  # Keycloak service for identity and access management
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - "9090:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    command:
      - start-dev
      - --db=dev-file

volumes:
    keycloak_data:
      driver: local